**ADVANCE INDEXING AND MANIPULATION**

In [1]:
 import numpy  as np

In [6]:
arr = np.array([1,2,3,4,5])
arr[[0,2]] #by using double sqaure brackets u r able to access two indexing at a tym

array([1, 3])

In [19]:
mat = np.arange(1,21).reshape(4,5)
print(mat)
#mat[[rows],[coloumns]]
mat[[0,1,3],[0,1,4]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([ 1,  7, 20])

**CONDITIONAL SELECTION**

In [28]:
arr = np.array([10,20,30,40,50,60])
bool_num = print(arr[arr>20])
boolean_val = print(arr>20)
index_location = print(np.where(arr>20))#tells the index location based on the condition 
reserve_replacing = print(np.where(arr>20,arr,0))
#np.where(check-condition,reserve-variable,replace with)

[30 40 50 60]
[False False  True  True  True  True]
(array([2, 3, 4, 5]),)
[ 0  0 30 40 50 60]


**SORTING & ORDERING**

In [32]:
arr = np.array([10,200,204,36,1,20,20,10,30,60])
sorted_array = print(np.sort(arr))
sort_indexes = print(np.argsort(arr))

[  1  10  10  20  20  30  36  60 200 204]
[4 0 7 5 6 8 3 9 1 2]


**CONCATENATION & STACKING**

In [35]:
a = np.array([1,2,3])
b = np.array([4,5,6])
conc = print(np.concat([a,b])) 

[1 2 3 4 5 6]
