In [23]:
import numpy as np 

In [24]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [25]:
vector_sum = a1 + a2 
vector_sum

array([ 7,  9, 11, 13, 15])

In [26]:
vector_sub = a1 - a2 , a2 - a1
vector_sub

(array([-5, -5, -5, -5, -5]), array([5, 5, 5, 5, 5]))

In [27]:
vector_multi = a1*a2
vector_multi

array([ 6, 14, 24, 36, 50])

In [28]:
vector_float = a1/a2 , a2/a1
vector_float

(array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ]),
 array([6.        , 3.5       , 2.66666667, 2.25      , 2.        ]))

In [29]:
vector_div = a1//a2 , a2//a1
vector_div

(array([0, 0, 0, 0, 0]), array([6, 3, 2, 2, 2]))

In [30]:
vector_mod = a1 % a2 , a2%a1
vector_mod

(array([1, 2, 3, 4, 5]), array([0, 1, 2, 1, 0]))

In [31]:
vector_expo = a1**a2
vector_expo

array([      1,     128,    6561,  262144, 9765625])

In [32]:
arr = np.array([10,20,30,40,50,60])
arr

array([10, 20, 30, 40, 50, 60])

In [33]:
arr + 100

array([110, 120, 130, 140, 150, 160])

In [34]:
matrix = np.arange(1,31).reshape(6,5)
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [35]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [36]:
slicing = a[0:5]
slicing =slicing*10
slicing

array([10, 20, 30, 40, 50])

In [37]:
a # a will remain same as previous and the concept called shallow copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [38]:
a = np.array([1,2,3,4,5])
b = a  # concept of deep copy
b 

array([1, 2, 3, 4, 5])

In [39]:
b[1] = 18
a

array([ 1, 18,  3,  4,  5])

In [40]:
b # the whole array is change as the ocation of both the arrays are same

array([ 1, 18,  3,  4,  5])

In [41]:
a = np.array([1,2,3,4,5])
b = a.copy() # by using copy method u can make this shallow copy and the output will be different 
b 

array([1, 2, 3, 4, 5])

In [42]:
b[0] = 99
b

array([99,  2,  3,  4,  5])

In [43]:
a

array([1, 2, 3, 4, 5])

In [44]:
mat1 = np.array([[4,5],[6,7]])
mat2 = np.array([[2,1],[0,2]])
mat1

array([[4, 5],
       [6, 7]])

In [45]:
mat2

array([[2, 1],
       [0, 2]])

In [46]:
mat1@mat2

array([[ 8, 14],
       [12, 20]])

In [47]:
matrix1 = np.arange(1,10).reshape(3,3)
matrix2 = np.arange(11,20).reshape(3,3)
matrix1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
matrix2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [49]:
np.dot(matrix1,matrix2)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [50]:
transpose = np.arange(1,10).reshape(3,3)
transpose

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
transpose.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [52]:
a = np.array([1,2,3,4])
b = np.array([6,7,8,9])
a

array([1, 2, 3, 4])

In [53]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [54]:
np.hstack((a,b))

array([1, 2, 3, 4, 6, 7, 8, 9])

In [55]:
np.column_stack((a,b))

array([[1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [56]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [57]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [58]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]