In [1]:
import numpy as np

**Basic Array creation**

In [2]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
a = [1,2,3.5]
print(np.array(a))

[1.  2.  3.5]


In [4]:
l = [[1,2,3],[4,5,6],[7,8,9]]
print(np.array(l))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**Array generation function**

In [5]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [6]:
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [8]:
arr = np.linspace(10,1,10)
arr

array([10.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.])

**Random Generation function**

In [9]:
print(np.random.rand(5))
print(np.random.randn(10))
print(np.random.randint(10,20,10))

[0.1255549  0.66745016 0.70374147 0.57212358 0.59816919]
[-0.8891376  -1.05537018  1.5613837   1.11347734  0.78042179  0.35469253
  0.27001245 -0.73541505  0.36672886 -0.47027703]
[17 11 11 14 12 10 12 15 10 12]


**Array Attributes**

In [10]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
print(arr.shape)
print(arr.size)
print(arr.dtype)

(3, 3)
9
int64


**Array Methods**

In [12]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])  
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
print(arr.min())
print(arr.max())
print(arr.sum())
print(np.sum(arr,axis = 1))
print(arr.mean())
print(arr.std())
print(arr.argmax())
print(arr.argmin())

1
9
45
[ 6 15 24]
5.0
2.581988897471611
8
0


**Reshaping and resizing**

In [14]:
arr = np.arange(1,31)
arr
print(arr.reshape(6,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
