In [1]:
import numpy as np

In [2]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [3]:
arr[5]

np.int64(6)

In [4]:
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [5]:
arr[1:21:2]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
arr[1:21:3]

array([ 2,  5,  8, 11, 14, 17, 20])

In [7]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [8]:
arr[0]

array([1, 2, 3, 4, 5])

In [9]:
arr[5]

array([26, 27, 28, 29, 30])

In [10]:
arr[0,4]

np.int64(5)

In [11]:
arr[3:6,3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [12]:
arr[1:5,1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [13]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [14]:
arr[2]

array([11, 12, 13, 14, 15])

In [15]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [16]:
print(arr)
bool_indexing = arr%2==0
bool_indexing

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [17]:
arr = arr[bool_indexing]
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [18]:
arr1 = np.arange(0,31)
arr1
prime_num = arr1[arr1%3==2]
prime_num

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29])

In [19]:
prime_bool = [arr1%3==2]
prime_bool

[array([False, False,  True, False, False,  True, False, False,  True,
        False, False,  True, False, False,  True, False, False,  True,
        False, False,  True, False, False,  True, False, False,  True,
        False, False,  True, False])]