In [1]:
import numpy as np

In [2]:
a = np.arange(1,31).reshape(6,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [3]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [4]:
s.sum()

np.int64(405)

In [5]:
b = np.sum(s,axis = 1)
for i in b :
    if i != 45:
        print("Suduko is not valid")
        break
else:
    print("For rows suduko is valid")

For rows suduko is valid


In [6]:
np.sum(s,axis = 0)
b = np.sum(s,axis = 0)
for i in b :
    if i != 45:
        print("Suduko is not valid")
        break
else:
    print("For coloumn suduko is valid")

For coloumn suduko is valid


In [7]:
check3 = s[:3,6:9]
check3

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [8]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


In [9]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [10]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [11]:
#Find the average age of students.
students = data[0:6,0:1]
print("no of the ages ",students)
average = np.mean(students)
print(average)

no of the ages  [[18]
 [19]
 [17]
 [18]
 [20]]
18.4


In [12]:
#Extract Math marks of all students.
maths_marks = data[ : , 1:2]
maths_marks

array([[85],
       [92],
       [76],
       [65],
       [90]])

In [13]:
#Find the highest Science mark.
np.max(data[0:6, 2:])  

np.int64(95)

In [14]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1] > 90] 

array([[19, 92, 88]])

In [15]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [16]:
# Increase Math marks of all students by 5.
data[ : , 1:2]+=5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [17]:
#Find how many students are younger than 19.
len(data[data[0:6 ,0] < 19])
    

3

In [18]:
#Calculate the average marks in each subject (column-wise mean).
print(data)
m = np.mean(data[:,:],axis=0)
print(f"The coloumn wise average :",m)

[[18 90 78]
 [19 97 88]
 [17 81 95]
 [18 70 70]
 [20 95 85]]
The coloumn wise average : [18.4 86.6 83.2]


In [19]:
#Get data of students who scored at least 80 in two subjects.
data[(data[:, 1] >=80 ) & (data[: , 2] >=80)]


array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [ ]:
#Replace all Science marks < 75 with 0.
data[0:6, 2:][data[0:6, 2:]<75] = 0
data


array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])